### ISSUE TITLE
Requirement URI not following OGC-NA policy

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/cdb-volume-11#1]
The requirement URI on page 8 of CDB 1.1 Vol 11 `http://opengis.net/spec/CDB/1.0/core/OveralConceptualModel` is not consistent with OGC-NA policy.

Please see Section 5.3 of [OGC-NA Name type specification - specification elements (10-103)](http://portal.opengeospatial.org/files/?artifact_id=39194)

The base should be `http://www.opengis.net/spec`, so the 'www' is missing.

The URI is also missing a `/req/` segment.

**Comment by DavidFLOR** [comment]
draft V1.3 edited to insert the missing "www".  I don't know how to address the comment in the issue about a missing /req/ segment.  This is in a document titled REQ001.adoc in CDB-VOLUME-11 Github repo; a pull request with the exact recommendation for what is missing would be helpful

**Comment by DavidFLOR** [comment]
Added /req/ where appropriate for requirements URI in two instances
