### ISSUE TITLE
Conformance class URI not following OGC-NA policy

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/cdb-volume-11#2]
The conformance class URI on page 32 of CDB 1.1 Vol 11 `http://opengis.net/spec/CDB/1.0//conf/core/core/OveralConceptualModel` is not consistent with OGC-NA policy.

Please see Section 5.4 of [OGC-NA Name type specification - specification elements (10-103)](http://portal.opengeospatial.org/files/?artifact_id=39194)

The base should be `http://www.opengis.net/spec`, so the 'www' is missing.

Note as well that the URI appears to have a blank segment `//`, which should be removed.

**Comment by DavidFLOR** [comment]
Corrected in draft V1.3  "www" inserted as suggested.  The empty clause is already gone from some previous edit
